Redesigned FAQs page
coderwassananmol/BUB2 pull request #182
Opened 2023-10-04 16:50 UTC by Ed-Gah

## Redesigned for _[T340385](https://phabricator.wikimedia.org/T340385)_.

## Proposed Changes
- Created a faqs page
- Implemented a display component for the FAQs and answers
- Implemented an approach to persist Navbar and footer on the respective positions

## Files Added
- `components/FaqsSection.js`
- `pages/faqs.js`

## File Updated
- `components/Header.js`.

## Checked
Codebase structure followed :+1:

## Visual Results
![Screenshot of proposed implementation of Redesigning FAQs page](https://github.com/coderwassananmol/BUB2/assets/88565289/402a29bf-6de7-43b4-95be-dfdb23fafe74)

2023-10-05 09:36 UTC, Ed-Gah commented
### Fixes based on comments

## File Restored
`.env.example`

## Files updated
`components/FaqsSection.js`
`pages/faqs.js`
`package.json`

## Visual Results
![Screenshot from 2023-10-05 10-28-29](https://github.com/coderwassananmol/BUB2/assets/88565289/7a5e1f4b-4962-4389-9532-c7f3060de8b1)

2023-10-06 08:53 UTC, Parthiv-M commented
The `pages/api/auth/[...nextauth].js` does not have to be changed. Those details are only for the dev environment

2023-10-06 09:56 UTC, Ed-Gah commented
## Fixes on task [T340385](https://phabricator.wikimedia.org/T340385) based comments

## File Updated
`pages/api/auth/[...nextauth].js

2023-10-07 14:20 UTC, Parthiv-M commented
Couple of minor edits, otherwise good to go

2023-10-07 14:27 UTC, Parthiv-M commented
Couple of minor edits to the content, rest is good to go
- **_to be archived(which)_** to be changed to **_to be archived (which)_**
- **_So it doesn't support_** to be changed to  **_So it is not supported_** 
- Under _What are the future enhancements?_, the answer can be changed to **_Bulk upload feature, direct upload to Wikimedia Commons and addition of newer libraries are some features being actively worked upon_**

2023-10-07 14:55 UTC, Ed-Gah commented
Minor edits done Sir

2023-10-07 14:55 UTC, Parthiv-M approved these changes
LGTM

2023-10-08 19:49 UTC, coderwassananmol requested changes
Please pull the latest changes from the `develop` branch and make the requested change. Rest is good to go. :)

2023-10-08 19:49 UTC, coderwassananmol commented on pages/api/auth/[...nextauth].js
Please undo the changes made to this file.

2023-10-09 07:26 UTC, Ed-Gah commented
Done Sir

2023-10-09 19:45 UTC, coderwassananmol requested changes

2023-10-09 19:45 UTC, coderwassananmol commented on pages/api/auth/[...nextauth].js
> +      clientSecret: process.env.WIKIMEDIA_CLIENT_SECRET,
@Ed-Gah Please remove "," from here.

2023-10-09 19:45 UTC, coderwassananmol commented on pages/api/auth/[...nextauth].js
> +    }),
Please remove "," from here.

2023-10-10 05:51 UTC, Ed-Gah commented
Actually Sir, its removed since yesterday. But  when to commit and push husky sees it as an empty commit
![Screenshot from 2023-10-09 09-24-12](https://github.com/coderwassananmol/BUB2/assets/88565289/c6de3645-3f06-462e-9d58-c709cb3bbfdf)

2023-10-10 19:09 UTC, coderwassananmol commented
Okay. Closing this then.

2023-10-10 19:09 UTC, closed without merging