Fixes: [T354304]: Integrate PDL to Commons
coderwassananmol/BUB2 pull request #237
Opened 2024-01-03 20:12 UTC by okerekechinweotito

## Proposed Changes
- All proposed changes present in #233 apply here (UI Feedbacks , OAuth2 access token and upload to Commons
- For PDL, figure out a way to create a valid PDF file using the zipped images and then upload the PDF to Commons (as that would be easier to use on Wikisource than individually uploading the book page images).

2024-02-03 14:54 UTC, coderwassananmol requested changes
Add JSON.stringify while logging if the variable is an Object

2024-03-03 17:35 UTC, coderwassananmol commented
@okerekechinweotito Just tested. Here's the feedback:
1. We are logging and sending highly secure content like OAuth token to Internet Archive which could pose huge security risks. Please do not log and store the OAuth token anywhere.
2. Fields such as Commonsmetadata, Isuploadcommons, Oauthtoken should not be sent to Internet Archive.
3. If the PDL file is of zip type, the file upload to Commons is not working.

Sample IA file with error: https://archive.org/details/KhalsaAkhbarLahore2August1901
Sample PDL file of zip type: http://www.panjabdigilib.org/webuser/searches/displayPage.jsp?ID=682&page=1&CategoryID=5&Searched=

2024-03-08 09:26 UTC, okerekechinweotito commented on bull/commons-queue/consumer.js
> +        message: `downloadFile: ${downloadFileRes}`,
@coderwassananmol 
I checked the error log - downloadFileRes is not an object

2024-03-19 04:25 UTC, Parthiv-M commented
Couple of things after testing:
- I also find the _Username_ field on the [IA metadata list](https://archive.org/details/werwetcwe). That needs to be removed as well, I figure.
- `{"level":"error","message":"allJobs getJobs TypeError: Cannot read properties of null (reading 'step')","timestamp":"2024-03-19T00:16:22.981Z"}` got this in my logs when upload to commons hits 50%

Rest seems okay

2024-03-19 20:42 UTC, okerekechinweotito commented
@Parthiv-M 
I have removed userName

2024-03-30 11:28 UTC, coderwassananmol commented
@okerekechinweotito We shouldn't even be logging `oauthtoken` and using or sending it explicitly between components unless **absolutely** required.

2024-03-30 11:34 UTC, okerekechinweotito commented
> @okerekechinweotito We shouldn't even be logging `oauthtoken` and using or sending it explicitly between components unless **absolutely** required.
Alright. Please can you have another review

2024-03-31 06:56 UTC, coderwassananmol requested changes

2024-03-31 06:56 UTC, coderwassananmol commented on utils/helper.js
> +      console.log(" title:", title);
Remove console.log statement.

2024-03-31 06:56 UTC, coderwassananmol commented on bull/pdl-queue/producer.js
> +  metaData["oauthToken"] = oauthToken;
Why is oauthToken required?

2024-03-31 06:56 UTC, coderwassananmol commented on bull/pdl-queue/producer.js
> +  oauthToken,
Same here.

2024-04-02 08:28 UTC, okerekechinweotito commented on utils/helper.js
> +      console.log(" title:", title);
@coderwassananmol done

2024-05-03 08:53 UTC, coderwassananmol approved these changes

2024-05-03 08:53 UTC, merged